import { type NextPage } from "next";
import Head from "next/head";
import { Box } from "@mui/material";

//Components
import Card from "../components/Card";

function Home() {
  return (
    <>
      <Head>
        <title>Anasayfa | Hopi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg flex flex-col items-center justify-center">
        <img
          src="https://img-hopi.mncdn.com/7b/56/7b568e98956149d08def3fe2402ac739.png"
          width={"75%"}
          height={"auto"} />
        <Box
          sx={{
            height: "auto",
            width: "80%",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-around",
            flexDirection: "row",
            marginTop: 10,
          }}
        >
          <Card
            imageUrl="https://img-hopi.mncdn.com/web-assets/4.24.2-ug1683631407/assets/img/icons/hopi-dunyasi.svg"
            title="Hopi Dünyası"
            description="Yüzlerce markada kampanyalara ek tekliflerle, yüzlerce dükkândan anında alışveriş yapma ve hop diye ödeme imkânı sunan akıllı alışveriş arkadaşı." />
          <Card
            imageUrl="https://img-hopi.mncdn.com/web-assets/4.24.2-ug1683631407/assets/img/icons/hopi-star.svg"
            title="Hopi’nin Faydaları"
            description="Yüzlerce markada sana özel kazançlı alışveriş fırsatları ile Hopishop’ta özel ürün seçkileri ve Hopipay Dijital Kart ile kolay ve güvenli ödeme imkânı sunar." />
          <Card
            imageUrl="https://img-hopi.mncdn.com/web-assets/4.24.2-ug1683631407/assets/img/icons/tikla-kazan.svg"
            title="Tıkla Kazan"
            description="“Tıkla Kazan” kampanyaları, markaların mevcut indirim ve  kampanyalarına ek, her alışverişte sepet tutarının belli  oranında Paracık kazandırır." />
          <Card
            imageUrl="https://img-hopi.mncdn.com/web-assets/4.24.2-ug1683631407/assets/img/icons/firsat-eklentisi.svg"
            title="Hopi Fırsat Eklentisi"
            description="Hopi Eklentisi’ni tarayıcına yükleyerek, internette  gönlünce dolaşırken yüzlerce markadaki kampanyalardan  anında haberdar olabilirsin." />
        </Box>
      </main>
    </>
  );
}

export default Home;
